version: "2.4"
services:
  pokedex:
    build:
      context: .
    extends:
      file: service.yml
      service: pokedex
    depends_on:
      - pokedex-migration
      - mongo-dev
      - mongo-test
    command: yarn start:watch
    volumes:
      - ./:/home/node/app:cached
    ports:
      - 4000:3000

  pokedex-migration:
    build:
      context: .
    extends:
      file: service.yml
      service: pokedex
    depends_on:
      - mongo-dev
    command: yarn run migrate
    volumes:
      - ./:/home/node/app:cached

  mongo-dev:
    image: mongo:4.2
    volumes:
      - ./initial-data:/initial-data:cached
    command: mongod

  mongo-test:
    image: mongo:4.2
    command: mongod
